create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  service text not null,
  operation text not null,
  success boolean not null default false,
  latency_ms integer,
  input_tokens bigint,
  output_tokens bigint,
  total_tokens bigint,
  credits numeric,
  request_count integer not null default 1,
  error_code text,
  http_status integer,
  retryable boolean,
  quota_related boolean,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint usage_events_request_count_nonnegative check (request_count >= 0),
  constraint usage_events_latency_nonnegative check (latency_ms is null or latency_ms >= 0),
  constraint usage_events_input_tokens_nonnegative check (input_tokens is null or input_tokens >= 0),
  constraint usage_events_output_tokens_nonnegative check (output_tokens is null or output_tokens >= 0),
  constraint usage_events_total_tokens_nonnegative check (total_tokens is null or total_tokens >= 0),
  constraint usage_events_credits_nonnegative check (credits is null or credits >= 0)
);

create index if not exists usage_events_occurred_at_idx
  on public.usage_events (occurred_at desc);

create index if not exists usage_events_provider_occurred_at_idx
  on public.usage_events (provider, occurred_at desc);

create index if not exists usage_events_service_occurred_at_idx
  on public.usage_events (service, occurred_at desc);

alter table public.usage_events enable row level security;

-- Usage events are written by the server with the service-role key.
-- No direct client read/write policy is created intentionally.
